spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8092/eureka/
server:
  port: 8001
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8092/eureka/
server:
  port: 8002